import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { MediaPlaceholder } from "@/components/media-placeholder";
import { SectionTitle, StatusBadge } from "@/components/layout";
import { getProject, projects } from "@/data/projects";
export function generateStaticParams(){return projects.map(project=>({slug:project.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const project=getProject(slug);return project?{title:project.name,description:project.summary}:{title:"Projet"}}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const project=getProject(slug);if(!project)notFound();return <>
<section className={`project-hero shell accent-${project.accent}`}><span className="eyebrow">{project.eyebrow}</span><h1>{project.name}</h1><p className="summary">{project.summary}</p><StatusBadge>Statut : {project.status}</StatusBadge><div className="project-meta"><div><span>Cible</span><strong>{project.target}</strong></div><div><span>Positionnement</span><strong>{project.positioning}</strong></div></div></section>
<section className="section alt"><div className="shell detail-grid"><article className="card"><span className="eyebrow">Le problème</span><h2>Pourquoi ce produit existe</h2><p>{project.problem}</p></article><article className="card"><span className="eyebrow">La solution</span><h2>Réponse produit</h2><p>{project.solution}</p></article></div></section>
<section className="section"><div className="shell"><SectionTitle eyebrow="Parcours" title="Workflow principal"/><div className="workflow">{project.workflow.map((item,index)=><div key={item}><span>{String(index+1).padStart(2,"0")}</span><strong>{item}</strong></div>)}</div></div></section>
<section className="section alt"><div className="shell detail-grid"><div><SectionTitle eyebrow="Fonctionnel" title="Fonctionnalités clés"/><ul className="list">{project.features.map(item=><li key={item}>{item}</li>)}</ul></div><div><SectionTitle eyebrow="Technique" title="Stack et rôle"/><div className="tags">{project.stack.map(item=><span key={item}>{item}</span>)}</div>{project.languages&&<div className="language-box">{project.languages.map(item=><strong key={item}>{item}</strong>)}</div>}<h3>Mon rôle</h3><ul className="list">{project.role.map(item=><li key={item}>{item}</li>)}</ul></div></div></section>
<section className="section"><div className="shell"><SectionTitle eyebrow="Visuels" title="Emplacements préparés pour les captures." text="Les screenshots seront ajoutés plus tard sans modifier la structure éditoriale ni les routes."/><div className="media-grid">{project.mediaSlots.map((slot,index)=><MediaPlaceholder key={slot.title} slot={slot} index={index}/>)}</div></div></section>
<section className="section alt"><div className="shell grid two"><div><SectionTitle eyebrow="Preuves" title="Ce que le projet démontre"/><ul className="list">{project.proof.map(item=><li key={item}>{item}</li>)}</ul></div><div><SectionTitle eyebrow="Apprentissages" title="Compétences consolidées"/><ul className="list">{project.learnings.map(item=><li key={item}>{item}</li>)}</ul></div></div></section>
<section className="section"><div className="shell"><SectionTitle eyebrow="Roadmap" title="Cible séparée de l’existant"/><div className="grid two">{project.roadmap.map((item,index)=><article className="card" key={item}><span className="eyebrow">Étape {index+1}</span><h3>{item}</h3></article>)}</div></div></section>
<section className="section"><div className="shell cta"><div><span className="eyebrow">Étude de cas</span><h2>Un besoin métier comparable ?</h2></div><Link className="btn" href="/contact">Échanger sur votre projet</Link></div></section></>}
