import Link from "next/link";
import { ProjectCard } from "@/components/project-card";
import { SectionTitle } from "@/components/layout";
import { projects } from "@/data/projects";
import { method, proofPoints, services } from "@/data/site";

export default function HomePage() {
  return <>
    <section className="hero shell">
      <div className="hero-copy"><span className="eyebrow">Full Stack Product Builder • Consultant • Formateur</span><h1>Je transforme des besoins métier complexes en <em>produits opérationnels.</em></h1><p>Je conçois des SaaS, applications métiers, marketplaces, systèmes IA et automatisations de bout en bout : stratégie, architecture, développement, paiements, données, tests et lancement.</p><div className="actions"><Link className="btn" href="/projets">Voir mes réalisations</Link><Link className="btn secondary" href="/contact">Parler de votre projet</Link><Link className="text-link inline" href="/formations">Découvrir les formations →</Link></div><div className="proofs">{proofPoints.map(([value,label])=><div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div>
      <div className="hero-visual" aria-label="Illustration animée du cycle produit"><div className="hero-core"><strong>Produit</strong><small>de bout en bout</small></div><span className="orbit o1">Stratégie</span><span className="orbit o2">Développement</span><span className="orbit o3">IA & data</span><span className="orbit o4">Lancement</span></div>
    </section>
    <section className="section alt"><div className="shell"><SectionTitle eyebrow="Capacité globale" title="Comprendre, structurer, construire." text="Le site ne présente pas seulement des technologies : il montre la capacité à transformer un métier, des données et des contraintes en produit exploitable."/><div className="grid three"><article className="card"><span className="eyebrow">01 — Concevoir</span><h3>Produit, MVP et architecture</h3><p>Analyse métier, rôles, workflows, données, roadmap, UX et monétisation.</p></article><article className="card"><span className="eyebrow">02 — Construire</span><h3>Full Stack, IA et paiements</h3><p>Frontend, backend, bases de données, Stripe, agents, automatisations et déploiement.</p></article><article className="card"><span className="eyebrow">03 — Accompagner</span><h3>Pilotage, business et formation</h3><p>Audit, coordination, entrepreneuriat, transformation digitale et transmission.</p></article></div></div></section>
    <section className="section"><div className="shell"><SectionTitle eyebrow="Études de cas" title="Des produits construits autour de métiers réels." text="Chaque projet indique son statut réel, les fonctionnalités développées et ce qui relève encore de la roadmap."/><div className="grid two">{projects.slice(0,4).map(project=><ProjectCard key={project.slug} project={project}/>)}</div><div className="center-action"><Link className="btn secondary" href="/projets">Voir tous les projets</Link></div></div></section>
    <section className="section alt"><div className="shell"><SectionTitle eyebrow="Services" title="Une intervention adaptée au niveau de maturité du projet."/><div className="grid three">{services.map(service=><article className="card" key={service.slug}><span className="eyebrow">{service.shortTitle}</span><h3>{service.title}</h3><p>{service.summary}</p><Link className="text-link" href={`/services/${service.slug}`}>Voir les livrables →</Link></article>)}</div></div></section>
    <section className="section"><div className="shell"><SectionTitle eyebrow="Méthode" title="Une chaîne de décision complète."/><div className="steps">{method.map(([number,title,text])=><article className="step" key={number}><b>{number}</b><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>
    <section className="section"><div className="shell cta"><div><span className="eyebrow">Prochaine étape</span><h2>Un produit à cadrer, reprendre ou automatiser ?</h2><p>Décrivez le contexte, les utilisateurs et le résultat attendu.</p></div><Link className="btn" href="/contact">Parler du projet</Link></div></section>
  </>;
}
