import type { Metadata } from "next";
import Link from "next/link";
import { PageIntro, SectionTitle } from "@/components/layout";
export const metadata: Metadata = { title: "À propos", description: "Parcours d’Élie Leligny, Product Builder Full Stack et fondateur de Livré d’un Clic SASU." };
const timeline=[
  ["01","WordPress & acquisition","Landing pages, Elementor, formulaires, SEO, automatisations et premiers parcours utilisateurs."],
  ["02","Marketplace avec prestataires","Spécifications, coordination de développeurs, Stripe, workflows, tests, recette et décision de refonte."],
  ["03","Passage au Full Stack","React, TypeScript, Next.js, Supabase, PostgreSQL, RLS, Python, MongoDB et déploiement cloud."],
  ["04","Création de produits métiers","France Reliance, RatioPro, Le Billot Pro et Parayon : services, restauration, métiers de bouche et sport."],
  ["05","Entrepreneuriat","Création et pilotage d’une SASU, offres, modèles économiques, gestion administrative, partenariats et commercialisation."],
  ["06","Conseil & formation","Transmission autour de l’IA, l’automatisation, le produit, la création d’entreprise, la transformation digitale et l’ESS."],
];
export default function AboutPage(){return <><PageIntro eyebrow="À propos" title="Un parcours construit par les produits." text="Mon profil combine développement, direction produit, entrepreneuriat, vente, marketing, gestion de projet et coordination technique."/><section className="section"><div className="shell"><SectionTitle eyebrow="Progression" title="De la première landing page aux architectures SaaS."/><div className="steps large">{timeline.map(([number,title,text])=><article className="step" key={number}><b>{number}</b><div><h2>{title}</h2><p>{text}</p></div></article>)}</div></div></section><section className="section alt"><div className="shell detail-grid"><article className="card"><span className="eyebrow">Différence</span><h2>Une vision transversale</h2><p>Je peux cadrer une offre, modéliser ses workflows, développer le produit, intégrer les paiements, automatiser les opérations et préparer sa commercialisation.</p></article><article className="card"><span className="eyebrow">Formation continue</span><h2>Business et gestion</h2><p>Préparation du BTS GPME, formation Conseiller Vente et autoformation continue en développement, IA, SaaS, automatisation, gestion et ESS.</p></article></div></section><section className="section"><div className="shell cta"><div><span className="eyebrow">Profil complet</span><h2>Voir l’expérience et les compétences détaillées.</h2></div><Link className="btn" href="/cv">Consulter le CV</Link></div></section></>}
